export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type AppRole = 'admin' | 'gsa_contributor' | 'bookkeeper';
export type InterpreterStatus = 'active' | 'inactive' | 'pending';
export type FacilityStatus = 'active' | 'inactive' | 'pending';
export type JobStatus = 'new' | 'outreach_in_progress' | 'confirmed' | 'complete' | 'ready_to_bill' | 'billed' | 'paid' | 'cancelled';
export type JobLocationType = 'in_person' | 'remote';
export type ContractStatus = 'not_sent' | 'sent' | 'signed';
export type InvoiceStatus = 'draft' | 'submitted' | 'paid';
export type PaymentMethod = 'zelle' | 'check';
export type BillStatus = 'queued' | 'paid';
export type OpportunitySource = 'direct' | 'agency' | 'gsa' | 'referral' | 'repeat' | 'other';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          first_name: string | null;
          last_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          first_name?: string | null;
          last_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          first_name?: string | null;
          last_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          role: AppRole;
        };
        Insert: {
          id?: string;
          user_id: string;
          role: AppRole;
        };
        Update: {
          id?: string;
          user_id?: string;
          role?: AppRole;
        };
      };
      interpreters: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          timezone: string | null;
          status: InterpreterStatus;
          rid_certified: boolean;
          nic_certified: boolean;
          other_certifications: string | null;
          rate_business_hours: number | null;
          rate_after_hours: number | null;
          rate_mileage: number | null;
          minimum_hours: number;
          eligible_emergency_fee: boolean;
          eligible_holiday_fee: boolean;
          payment_method: PaymentMethod | null;
          payment_details: string | null;
          contract_status: ContractStatus;
          contract_signed_date: string | null;
          w9_received: boolean;
          w9_received_date: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          timezone?: string | null;
          status?: InterpreterStatus;
          rid_certified?: boolean;
          nic_certified?: boolean;
          other_certifications?: string | null;
          rate_business_hours?: number | null;
          rate_after_hours?: number | null;
          rate_mileage?: number | null;
          minimum_hours?: number;
          eligible_emergency_fee?: boolean;
          eligible_holiday_fee?: boolean;
          payment_method?: PaymentMethod | null;
          payment_details?: string | null;
          contract_status?: ContractStatus;
          contract_signed_date?: string | null;
          w9_received?: boolean;
          w9_received_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          timezone?: string | null;
          status?: InterpreterStatus;
          rid_certified?: boolean;
          nic_certified?: boolean;
          other_certifications?: string | null;
          rate_business_hours?: number | null;
          rate_after_hours?: number | null;
          rate_mileage?: number | null;
          minimum_hours?: number;
          eligible_emergency_fee?: boolean;
          eligible_holiday_fee?: boolean;
          payment_method?: PaymentMethod | null;
          payment_details?: string | null;
          contract_status?: ContractStatus;
          contract_signed_date?: string | null;
          w9_received?: boolean;
          w9_received_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      facilities: {
        Row: {
          id: string;
          name: string;
          billing_name: string | null;
          billing_address: string | null;
          billing_city: string | null;
          billing_state: string | null;
          billing_zip: string | null;
          physical_address: string | null;
          physical_city: string | null;
          physical_state: string | null;
          physical_zip: string | null;
          admin_contact_name: string | null;
          admin_contact_phone: string | null;
          admin_contact_email: string | null;
          status: FacilityStatus;
          rate_business_hours: number | null;
          rate_after_hours: number | null;
          rate_mileage: number | null;
          minimum_billable_hours: number;
          emergency_fee: number | null;
          holiday_fee: number | null;
          invoice_prefix: string | null;
          billing_code: string | null;
          net_terms: number;
          contract_status: ContractStatus;
          contract_signed_date: string | null;
          is_gsa: boolean;
          contractor: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          billing_name?: string | null;
          billing_address?: string | null;
          billing_city?: string | null;
          billing_state?: string | null;
          billing_zip?: string | null;
          physical_address?: string | null;
          physical_city?: string | null;
          physical_state?: string | null;
          physical_zip?: string | null;
          admin_contact_name?: string | null;
          admin_contact_phone?: string | null;
          admin_contact_email?: string | null;
          status?: FacilityStatus;
          rate_business_hours?: number | null;
          rate_after_hours?: number | null;
          rate_mileage?: number | null;
          minimum_billable_hours?: number;
          emergency_fee?: number | null;
          holiday_fee?: number | null;
          invoice_prefix?: string | null;
          billing_code?: string | null;
          net_terms?: number;
          contract_status?: ContractStatus;
          contract_signed_date?: string | null;
          is_gsa?: boolean;
          contractor?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          billing_name?: string | null;
          billing_address?: string | null;
          billing_city?: string | null;
          billing_state?: string | null;
          billing_zip?: string | null;
          physical_address?: string | null;
          physical_city?: string | null;
          physical_state?: string | null;
          physical_zip?: string | null;
          admin_contact_name?: string | null;
          admin_contact_phone?: string | null;
          admin_contact_email?: string | null;
          status?: FacilityStatus;
          rate_business_hours?: number | null;
          rate_after_hours?: number | null;
          rate_mileage?: number | null;
          minimum_billable_hours?: number;
          emergency_fee?: number | null;
          holiday_fee?: number | null;
          invoice_prefix?: string | null;
          billing_code?: string | null;
          net_terms?: number;
          contract_status?: ContractStatus;
          contract_signed_date?: string | null;
          is_gsa?: boolean;
          contractor?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      jobs: {
        Row: {
          id: string;
          job_number: string;
          facility_id: string;
          interpreter_id: string | null;
          deaf_client_name: string | null;
          job_date: string;
          start_time: string;
          end_time: string;
          location_type: JobLocationType;
          location_address: string | null;
          location_city: string | null;
          location_state: string | null;
          location_zip: string | null;
          timezone: string | null;
          video_call_link: string | null;
          status: JobStatus;
          opportunity_source: OpportunitySource | null;
          business_hours_worked: number | null;
          after_hours_worked: number | null;
          actual_start_time: string | null;
          actual_end_time: string | null;
          facility_rate_business: number | null;
          facility_rate_after_hours: number | null;
          facility_rate_mileage: number | null;
          interpreter_rate_business: number | null;
          interpreter_rate_after_hours: number | null;
          interpreter_rate_mileage: number | null;
          mileage: number | null;
          parking: number | null;
          tolls: number | null;
          travel_time_hours: number | null;
          travel_time_rate: number | null;
          trilingual_rate_uplift: number | null;
          misc_fee: number | null;
          emergency_fee_applied: boolean;
          holiday_fee_applied: boolean;
          billable_hours: number | null;
          facility_hourly_total: number | null;
          facility_billable_total: number | null;
          interpreter_hourly_total: number | null;
          interpreter_billable_total: number | null;
          total_facility_charge: number | null;
          total_interpreter_pay: number | null;
          internal_notes: string | null;
          confirmation_sent_at: string | null;
          reminder_sent_at: string | null;
          invoice_reminder_sent_at: string | null;
          finalized_at: string | null;
          client_business_name: string | null;
          client_contact_name: string | null;
          client_contact_phone: string | null;
          client_contact_email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          job_number?: string;
          facility_id: string;
          interpreter_id?: string | null;
          deaf_client_name?: string | null;
          job_date: string;
          start_time: string;
          end_time: string;
          location_type?: JobLocationType;
          location_address?: string | null;
          location_city?: string | null;
          location_state?: string | null;
          location_zip?: string | null;
          timezone?: string | null;
          video_call_link?: string | null;
          status?: JobStatus;
          opportunity_source?: OpportunitySource | null;
          business_hours_worked?: number | null;
          after_hours_worked?: number | null;
          actual_start_time?: string | null;
          actual_end_time?: string | null;
          facility_rate_business?: number | null;
          facility_rate_after_hours?: number | null;
          facility_rate_mileage?: number | null;
          interpreter_rate_business?: number | null;
          interpreter_rate_after_hours?: number | null;
          interpreter_rate_mileage?: number | null;
          mileage?: number | null;
          parking?: number | null;
          tolls?: number | null;
          travel_time_hours?: number | null;
          travel_time_rate?: number | null;
          trilingual_rate_uplift?: number | null;
          misc_fee?: number | null;
          emergency_fee_applied?: boolean;
          holiday_fee_applied?: boolean;
          billable_hours?: number | null;
          facility_hourly_total?: number | null;
          facility_billable_total?: number | null;
          interpreter_hourly_total?: number | null;
          interpreter_billable_total?: number | null;
          total_facility_charge?: number | null;
          total_interpreter_pay?: number | null;
          internal_notes?: string | null;
          confirmation_sent_at?: string | null;
          reminder_sent_at?: string | null;
          invoice_reminder_sent_at?: string | null;
          finalized_at?: string | null;
          client_business_name?: string | null;
          client_contact_name?: string | null;
          client_contact_phone?: string | null;
          client_contact_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          job_number?: string;
          facility_id?: string;
          interpreter_id?: string | null;
          deaf_client_name?: string | null;
          job_date?: string;
          start_time?: string;
          end_time?: string;
          location_type?: JobLocationType;
          location_address?: string | null;
          location_city?: string | null;
          location_state?: string | null;
          location_zip?: string | null;
          timezone?: string | null;
          video_call_link?: string | null;
          status?: JobStatus;
          opportunity_source?: OpportunitySource | null;
          business_hours_worked?: number | null;
          after_hours_worked?: number | null;
          actual_start_time?: string | null;
          actual_end_time?: string | null;
          facility_rate_business?: number | null;
          facility_rate_after_hours?: number | null;
          facility_rate_mileage?: number | null;
          interpreter_rate_business?: number | null;
          interpreter_rate_after_hours?: number | null;
          interpreter_rate_mileage?: number | null;
          mileage?: number | null;
          parking?: number | null;
          tolls?: number | null;
          travel_time_hours?: number | null;
          travel_time_rate?: number | null;
          trilingual_rate_uplift?: number | null;
          misc_fee?: number | null;
          emergency_fee_applied?: boolean;
          holiday_fee_applied?: boolean;
          billable_hours?: number | null;
          facility_hourly_total?: number | null;
          facility_billable_total?: number | null;
          interpreter_hourly_total?: number | null;
          interpreter_billable_total?: number | null;
          total_facility_charge?: number | null;
          total_interpreter_pay?: number | null;
          internal_notes?: string | null;
          confirmation_sent_at?: string | null;
          reminder_sent_at?: string | null;
          invoice_reminder_sent_at?: string | null;
          finalized_at?: string | null;
          client_business_name?: string | null;
          client_contact_name?: string | null;
          client_contact_phone?: string | null;
          client_contact_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          invoice_number: string;
          facility_id: string;
          status: InvoiceStatus;
          subtotal: number;
          tax: number;
          total: number;
          issued_date: string | null;
          due_date: string | null;
          paid_date: string | null;
          quickbooks_invoice_id: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          invoice_number: string;
          facility_id: string;
          status?: InvoiceStatus;
          subtotal?: number;
          tax?: number;
          total?: number;
          issued_date?: string | null;
          due_date?: string | null;
          paid_date?: string | null;
          quickbooks_invoice_id?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          invoice_number?: string;
          facility_id?: string;
          status?: InvoiceStatus;
          subtotal?: number;
          tax?: number;
          total?: number;
          issued_date?: string | null;
          due_date?: string | null;
          paid_date?: string | null;
          quickbooks_invoice_id?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoice_items: {
        Row: {
          id: string;
          invoice_id: string;
          job_id: string | null;
          description: string;
          quantity: number;
          unit_price: number;
          total: number;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          job_id?: string | null;
          description: string;
          quantity: number;
          unit_price: number;
          total: number;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          job_id?: string | null;
          description?: string;
          quantity?: number;
          unit_price?: number;
          total?: number;
        };
      };
      interpreter_bills: {
        Row: {
          id: string;
          interpreter_id: string;
          job_id: string;
          status: BillStatus;
          hours_amount: number;
          mileage_amount: number;
          expenses_amount: number;
          total: number;
          pay_period_start: string | null;
          pay_period_end: string | null;
          paid_date: string | null;
          payment_method: PaymentMethod | null;
          payment_reference: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          interpreter_id: string;
          job_id: string;
          status?: BillStatus;
          hours_amount?: number;
          mileage_amount?: number;
          expenses_amount?: number;
          total?: number;
          pay_period_start?: string | null;
          pay_period_end?: string | null;
          paid_date?: string | null;
          payment_method?: PaymentMethod | null;
          payment_reference?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          interpreter_id?: string;
          job_id?: string;
          status?: BillStatus;
          hours_amount?: number;
          mileage_amount?: number;
          expenses_amount?: number;
          total?: number;
          pay_period_start?: string | null;
          pay_period_end?: string | null;
          paid_date?: string | null;
          payment_method?: PaymentMethod | null;
          payment_reference?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      email_templates: {
        Row: {
          id: string;
          name: string;
          subject: string;
          body: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          subject: string;
          body: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          subject?: string;
          body?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      email_logs: {
        Row: {
          id: string;
          job_id: string | null;
          interpreter_id: string | null;
          facility_id: string | null;
          template_name: string | null;
          recipient_email: string;
          subject: string;
          status: string;
          sent_at: string;
        };
        Insert: {
          id?: string;
          job_id?: string | null;
          interpreter_id?: string | null;
          facility_id?: string | null;
          template_name?: string | null;
          recipient_email: string;
          subject: string;
          status?: string;
          sent_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string | null;
          interpreter_id?: string | null;
          facility_id?: string | null;
          template_name?: string | null;
          recipient_email?: string;
          subject?: string;
          status?: string;
          sent_at?: string;
        };
      };
    };
    Views: {};
    Functions: {
      has_role: {
        Args: { _user_id: string; _role: AppRole };
        Returns: boolean;
      };
      is_team_member: {
        Args: { _user_id: string };
        Returns: boolean;
      };
    };
    Enums: {
      app_role: AppRole;
      interpreter_status: InterpreterStatus;
      facility_status: FacilityStatus;
      job_status: JobStatus;
      job_location_type: JobLocationType;
      contract_status: ContractStatus;
      invoice_status: InvoiceStatus;
      payment_method: PaymentMethod;
      bill_status: BillStatus;
      opportunity_source: OpportunitySource;
    };
  };
}
