-- Insert interpreter data from CSV import (only records with valid emails)
INSERT INTO public.interpreters (first_name, last_name, email, rate_business_hours, rate_after_hours, address, city, state, notes, payment_method, status)
VALUES
  ('Aaron', 'Brewer', 'breweraaronm@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Teodora', 'Acevedo-Palma', 'aatirla@gmail.com', 45.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Adam', 'Janisieski-Chacon', 'adam.janisieski@gmail.com', 49.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Adrianne', 'Clegg', 'adrianneclegg@gmail.com', 61.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Adrienne', 'Kearney', 'adriennekearney@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Adrienne', 'Bodisch', 'temporaryag@hotmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Akeya', 'Poeples', 'akeya80@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Alan', 'Hocker', '1alanhocker13@gmail.com', 45.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Alecia', 'Cole', 'artsigns.ac@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Alexandria', 'Pucciarelli', 'alexandria.pucciarelli@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Alicia', 'Davidovich', 'abdavido@comcast.net', 75.00, NULL, NULL, NULL, NULL, 'RID# 11663', 'zelle', 'active'),
  ('Alicia', 'Mcclurkan', 'CDIbookme@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Alisha', 'Bronk', 'zaslcl@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Allisum', 'Kale', 'allisunkale@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Alonso', 'Rivera', 'alonso.rivera181@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Alyson', 'Bass', 'alysonbass5@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Alyssa', 'Lardi', 'alyssamlardi@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Amanda', 'Allard', 'allard524@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Amanda', 'Wittman', 'wittman.amanda@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Amy', 'Davitan', 'mimi.davit@gmail.com', 62.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Amy', 'Rubinger', 'amyrubinger@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Ana', 'Pimenta', 'anapimentas@outlook.com', 40.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Andrea', 'Murphy', 'wlsgn4u@yahoo.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Andrew', 'Galuskin', 'andrewgaluskin@gmail.com', 65.00, 70.00, NULL, NULL, NULL, 'RID# 74156', 'zelle', 'active'),
  ('Andria', 'Alefhi', 'aslamberton@gmail.com', 65.00, 80.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Anna', 'Carter', 'acarterinterpret@yahoo.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('AnnMarie', 'Frankenstein', 'amfrankenstein@hotmail.com', 50.00, NULL, NULL, 'Columbus', 'Ohio', NULL, 'zelle', 'active'),
  ('Anthony', 'Downey', 'downey4874@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Ashley', 'Rosskowski', 'ashleyrosskowski@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Ashley', 'Stough', 'ashley.t.stough@gmail.com', 70.00, NULL, NULL, NULL, NULL, 'RID# 79582', 'zelle', 'active'),
  ('Audrey', 'Bastian', 'audrey.bastian@gmail.com', 100.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Audrey', 'Creed', 'audreyanncreed@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Audrey', 'Rosenberg', 'audie0217@gmail.com', 65.00, 70.00, 'PO Box 2533', 'Edison', 'NJ', NULL, 'zelle', 'active'),
  ('Barry', 'Barlow', 'bbarlowrver@gmail.com', 70.00, NULL, '1797 Ardith Dr', 'Pleasant Hill', 'Ca', 'RID# 37542', 'zelle', 'active'),
  ('Becky', 'Brady', 'bradymbjmr@juno.com', 42.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Beth', 'Kovatch', 'visuallyfluent@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Beth', 'McNelis', 'elizabethmcnelis@gmail.com', 55.00, 65.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Beth', 'Zuriff', 'bzuriff@gmail.com', 70.00, 80.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Beth Ann', 'Armstong', 'bethannkful@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Bill', 'Green', 'billandroberta@att.net', 40.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Billieanne', 'McLellan', 'beai@sign911interpreting.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'check', 'active'),
  ('Bonnie', 'Womack', 'bonnie.womack@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Brandy', 'Davis', 'bdavisaslinterpreter@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Brenda', 'Adkinson', 'brendaadkinson@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Brenda', 'Stansbury', 'brendaclassact@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Brian', 'Ambrose', 'bwambrose@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Brian', 'Millin', 'brian.millin@gmail.com', 70.00, NULL, '13654 Lower Edgemont Rd', 'Waynesboro', 'Pa', 'RID# 47490', 'zelle', 'active'),
  ('Bridget', 'Meyer', 'bridgetmorinameyer@gmail.com', 70.00, NULL, NULL, NULL, NULL, 'no zelle/ send check', 'check', 'active'),
  ('Brittany', 'Alvarez', 'brittany.d.alvarez@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Caleigh', 'McKenna', 'calmckenna@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Candace', 'Davider', 'candaceterp@gmail.com', 65.00, 119.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cara', 'Biuso', 'csign55@aol.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Carlo', 'Jaramillo', 'carlojaramillo@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Carol', 'McLaggan', 'signersj@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Carol', 'Uckar', 'uckarc@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Caroline', 'Keenan', 'carolineekeenann@gmail.com', 45.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cass', 'DelCastillo', 'cassofthecastle@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Caterina', 'Phillips', 'caterinaphillips@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Catrina', 'White', 'interpretercat@gmail.com', 75.00, NULL, NULL, NULL, NULL, 'RID# 20201', 'zelle', 'active'),
  ('CC Celeste', 'Rowe', 'cc.rowe@icloud.com', 100.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cecelia', 'Lopez', 'cecilopezny@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cedar', 'Jones', 'cedarsinai@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Chanel', 'Whalen', 'chanelkwhalen@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cheryl', 'Pfieffer', 'kardiafocus@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cheryl', 'Vail', 'cvcict@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cheryl', 'Garrett', 'garrettcheryl@yahoo.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cheryl', 'Ringel', 'signlanguageinterpreting@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Christina', 'Calder', 'ccalderterp@gmail.com', 45.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Christina', 'Intartaglia', 'cintartaglia@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Christina', 'Alton', 'christinaalton@gmail.com', 50.00, NULL, NULL, NULL, NULL, 'RID# 63380', 'zelle', 'active'),
  ('Christine', 'Iannone', 'gruvyknees@yahoo.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Christine', 'Martin', 'christinesnydermartin@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Christine', 'Duez', 'cduez10@yahoo.com', 60.00, NULL, NULL, NULL, NULL, 'RID# 13176', 'zelle', 'active'),
  ('Christine', 'Kanta', 'christinekanta@gmail.com', 85.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Christy', 'Hennessey', 'chcurly@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cindy', 'Loveless', 'crbryant54@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cindy', 'Hsu', 'candicechsu@gmail.com', 60.00, NULL, NULL, NULL, NULL, 'CDI', 'zelle', 'active'),
  ('Cj', 'Hartsock', 'cjhsigns@aol.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Claire', 'Youkilis Shafer', 'claireyoukilis@yahoo.com', 80.00, NULL, NULL, NULL, NULL, 'RID# 53560', 'zelle', 'active'),
  ('Clare', 'Backman Sullivan', 'cbachmaninterpreting@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Corey', 'Wys', 'corey_wys@yahoo.com', 55.00, NULL, NULL, NULL, NULL, 'RID# 72405', 'zelle', 'active'),
  ('Cory', 'Watson', 'terpcoryjean@gmail.com', 80.00, NULL, NULL, NULL, NULL, 'RID# 34256', 'zelle', 'active'),
  ('Cq', 'Unknown', 'cqterp@gmail.com', 70.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cristine', 'Saunders', 'saunders.cristine@gmail.com', 70.00, NULL, '2765 Lakehurst', 'Ann Arbor', 'MI', NULL, 'zelle', 'active'),
  ('Cynthia', 'Norman', 'cynthiajnormaninterpreter@gmail.com', 100.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cynthia', 'Concavage', 'cwc310@att.net', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Daisy', 'Dipple', 'daisykayp@yahoo.com', 50.00, NULL, NULL, 'Hot Springs', 'Ak', NULL, 'zelle', 'active'),
  ('Daisy', 'Cardenas', 'didihulklady@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Dana', 'Fontana', 'danav.fontana@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Darlene', 'Rochkind', 'darlene.m.chan@gmail.com', 80.00, NULL, NULL, NULL, NULL, 'non cert', 'zelle', 'active'),
  ('David', 'Mulford', 'dwmterp@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('David', 'Leitson', 'davidleitson@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Dawn', 'Duran', 'dawn@lighthouseasl.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Debbie', 'Chesser', 'dchesser03@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Debbie', 'Mancuso', 'dmancusoterp@gmail.com', 75.00, NULL, NULL, NULL, NULL, 'no zelle/ send check', 'check', 'active'),
  ('Deborah', 'Diaz', 'deileen4747@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Deborah', 'Bettencourt', 'handsfly2@yahoo.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Delaney', 'Toone', 'delaneymtoone@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Delia', 'DAngelo', 'dollynk@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Denise', 'Corino', 'dsign1118@aol.com', 75.00, 85.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Denise', 'Kahler', 'deniseakahler@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Diane', 'Barkstrom', 'dianebarkasl@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Dianne', 'Nosch', 'diannenosch95@gmail.com', 60.00, 75.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Dion', 'McCray', 'dionterp95@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Donna', 'McCole', 'interpreter@donnamccole.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Doreen', 'Capofari', 'dorcap24@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Edward', 'Knight', 'codaknightbros@gmail.com', 85.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Elaine', 'Hernandez', 'hernandez.elaine@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Elise', 'Melito', 'elise.melito@gmail.com', 70.00, 80.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Elle', 'Langevin', 'ellelangevin@gmail.com', 72.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Elyse', 'Real', 'realinterpreting@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Emily', 'Turner', 'turner.interpreting@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Erica', 'Allen', 'ericaterp@gmail.com', 80.00, NULL, NULL, NULL, NULL, 'no zelle/ send check', 'check', 'active'),
  ('Erika', 'DaSilva', 'dasilvaterp@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Erika', 'Murray', 'erikannm@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Erin', 'Frost', 'erinmfrost@gmail.com', 55.00, 60.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Faith', 'Pritchard', 'faith.pritchard@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Felice', 'Shays', 'missshays@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Gina', 'Puma', 'gpsurette@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Gregory', 'Lawson', 'gregorylawsonterp@outlook.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Gregory', 'Simpson', 'earlfitzz@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Hailey', 'Sweeney', 'hailey.interp@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Hedie', 'Kelly', 'hediekelly@gmail.com', 80.00, NULL, NULL, 'Philly', 'PA', NULL, 'zelle', 'active'),
  ('Helen', 'Young', 'accurateterp@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Hillary', 'Froitzheim', 'hillary.froitz@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Hope', 'Simon', 'hopeluvsasl@yahoo.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('I Ching', 'Ng', 'iching.ng@gmail.com', 60.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Ingrid', 'Sims', 'ingridsalazar0823@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Issac', 'Chavez', 'issac.chavez55@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jahmeca', 'Osborne', 'josborne513@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jaimie', 'Koelbel', 'jaimiekoelbel@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('James', 'Sewell', 'asluzer803@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jamie', 'Steinberg', 'jamieterpasl@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jamie', 'Niehuis', 'jamie.asl.interpreter@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jamieson', 'Harrington', '2lasts@gmail.com', 65.00, NULL, NULL, NULL, NULL, 'non-cert', 'zelle', 'active'),
  ('Jane', 'Hacker-Cain', 'janeheckercain@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Janet', 'Zibelli', 'zibellija@comcast.net', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jasmine', 'Monroy', 'monroy.jasmine@yahoo.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jason', 'Distelrath', 'jjdistelrath@yahoo.com', 85.00, 80.00, NULL, NULL, NULL, 'RID# 33314', 'zelle', 'active'),
  ('Jeffery', 'Bowden', 'jeffbow827@gmail.com', 65.00, NULL, NULL, NULL, NULL, 'RID# 82175', 'zelle', 'active'),
  ('Jennifer', 'Ingalls', 'jenniferingalls@yahoo.com', 65.00, NULL, NULL, NULL, NULL, 'RID# 56344', 'zelle', 'active'),
  ('Jennifer', 'Olson', 'jolson7@gmail.com', 100.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jennifer', 'Pelloni', 'jenniferpelloni@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jennifer', 'Profitt', 'jennp0587@gmail.com', 50.00, NULL, '1317 Urban Ave', 'Kettering', 'Ohio', NULL, 'zelle', 'active'),
  ('Jennifer', 'Restucci', 'jennybooks2@mac.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jennifer', 'Tester', 'jenniferatester@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jennifer', 'Ward', 'cert.terp@gmail.com', 65.00, NULL, NULL, NULL, NULL, 'RID# 51358', 'zelle', 'active'),
  ('Jerriann', 'Skinner', 'jerriskinner@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jessica', 'Ames', 'ames_jessica@hotmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jessica', 'Valenti', 'jbvalenti78@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jessica', 'Moore-Boetius', 'signmoore@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jill', 'Sege', 'segelaw@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jillian', 'Deaton', 'jilldeaton5@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jimmy', 'Granger', 'jimmy.interpreter@gmail.com', 90.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Joanne', 'Burns', 'jomamacosentino@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jody', 'Prysock', 'jodyprysock@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Joey', 'Gebbia', 'joeygebbia@outlook.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Johanna', 'Mery', 'johanna.terp@gmail.com', 50.00, NULL, NULL, NULL, NULL, 'RID# 48929', 'zelle', 'active'),
  ('John', 'Aintablian', 'jca532@sbcglobal.net', 60.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('John', 'Harvey', 'jon68j@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('John', 'Izaguirre', 'john.g.izaguirre@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jonathan', 'Lamberton', 'jonlamberton@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jose', 'Gomez', 'jlgomezjr@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jose', 'Rios', 'justo1025@hotmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Joseph', 'Desmond', 'joedesmond.interpreter@gmail.com', 60.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Joshua', 'Lane', 'joshualane.author@yahoo.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Joy', 'Harris', 'joyaharris@me.com', 85.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Julie', 'Balassa', 'whitefeatherinterpreting@tagracadabra.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Julie', 'Colton', 'tjcolton4@gmail.com', 40.00, 40.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kaitlin', 'Rickerd', 'kaitlinrickerd@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kara', 'Long', 'karalong75@gmail.com', 65.00, NULL, NULL, NULL, NULL, 'RID# 33692', 'zelle', 'active'),
  ('Karen', 'Boyle', 'karenmboyle@yahoo.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Karen', 'Bochette', 'karenbochette@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Karen', 'Maguire', 'maker528@verizon.net', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Karen', 'Staller', 'kbstaller@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Karen', 'Sexton', 'karenmommyof5@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Karen', 'Perez', 'perezovi@optonline.net', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kat', 'Katona', 'kat.katona@yahoo.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kathy', 'McAleer', 'mskathymac@yahoo.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kathy', 'Nelson', 'brownnil@yahoo.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Katie', 'Rickerd', 'rickerd.interpreting@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Katie Lee', 'Tiemeyer', 'signlanguagekate@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Keelin', 'Thomas', 'keelin.lambert@gmail.com', 85.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Keimi', 'Malave', 'keimi.malave01@gmail.com', 70.00, 80.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kelly', 'Winner', 'kellywinner@hotmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kerry', 'Patterson', 'pattersonkerry88@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kim', 'Mecane', 'kmecane@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kim', 'Melchert', 'melchertkimberly@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kimberly', 'Koste', 'kimkoste@gmail.com', 85.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kristi', 'Vacca', 'kristi@ksignsinc.com', 60.00, NULL, NULL, NULL, NULL, 'RID# 25481', 'zelle', 'active'),
  ('Kristin', 'Steinmetz Roselli', 'rosellikristin@gmail.com', 65.00, NULL, '602 Park Place', 'Springfield', 'NJ', NULL, 'zelle', 'active'),
  ('Kristina', 'Riley', 'krileyterp@gmail.com', 65.00, NULL, NULL, NULL, NULL, 'no zelle/ send check', 'check', 'active'),
  ('Kristy', 'Stiener', 'kristy.steiner@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kristy', 'Fuller', 'kristylynch44@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Krystal', 'Stutts', 'krystalstutts.asl@gmail.com', 52.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kwi', 'Hoon Lee', 'kwihoonlee@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kyle', 'Nye', 'kyle.nye.terp@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Laura', 'Brennan', 'laurabeth.terp@gmail.com', 75.00, NULL, NULL, NULL, NULL, 'RID# 49015', 'zelle', 'active'),
  ('Laura', 'Clark', 'lauraclark74@icloud.com', 85.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Laura', 'Temple', 'lauraetemple427@msn.com', 60.00, NULL, NULL, NULL, NULL, 'RID# 36207', 'zelle', 'active'),
  ('Laura', 'Ferguson', 'laura.ferguson6609@gmail.com', 65.00, NULL, '14650 Triple Crown LN', 'San Antonio', 'TX', 'no zelle/ send check', 'check', 'active'),
  ('Laurellie', 'Jacob', 'laurellie@yahoo.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Leah', 'Norman', 'jlbeardies@gmail.com', 65.00, 70.00, NULL, NULL, NULL, 'RID# 55465', 'zelle', 'active'),
  ('Leah', 'Rothman', 'henrylcr@gmail.com', 85.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Leana', 'Tapnack', 'leana.tapnack@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Leigh', 'Zarem', 'leighvz@gmail.com', 75.00, 80.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lilly', 'Davis', 'lildav16@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Linda', 'Campbell', 'lcampbellga@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Linda', 'Hardy', 'ladycict@aol.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lindsay', 'Kekoolani', 'lindsaydru@gmail.com', 45.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lindsey', 'Dancygier', 'lindsey.dancygier@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lisa', 'Campbell', 'lisadeafhandsconn@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lisa', 'Perry', 'lrp2go@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lisa', 'Balbirnie', 'lisabsigns@gmail.com', 80.00, NULL, '2208 N Lakewood Blvd. #8', 'Long Beach', 'CA', NULL, 'check', 'active'),
  ('Lisa', 'Dennett', 'ldennett@live.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lisa', 'Reynolds', 'lisareynoldsrs@gmail.com', 70.00, 80.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Liz', 'Palladino', 'lizpalladino@optonline.net', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lorena', 'Baker', 'lrsign4u@yahoo.com', 60.00, NULL, NULL, NULL, NULL, 'RID# 15955', 'zelle', 'active'),
  ('Lucia', 'Villar', 'love2sign.lcs@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lyndi', 'Gura', 'lyndisigns@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lynne', 'Cassell', 'lynnemariecassell3@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lynne', 'Martirano', 'lmartirano@comcast.net', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lynne', 'Watson', 'lynnew143@yahoo.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lynne', 'Doyle', 'lynnedoyle2664@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Maggie', 'Scarcella', 'mscarsella@northwell.edu', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Majorie', 'Foster', 'marjorie.foster@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Mallory', 'Cross', 'malloryinterpreting@gmail.com', 60.00, NULL, NULL, NULL, NULL, 'RID# 82493', 'zelle', 'active'),
  ('Mandy', 'Heinbaugh', 'msmandynyc@yahoo.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Mara', 'Zuckerman', 'marazucker@aol.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Marcus', 'Gunter', 'marcus.s.gunter@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Margie', 'Rodgers', 'margieasl4u@aol.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Margiori', 'Campos', 'Magicampos2001@gmail.com', 45.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Maria', 'Berggoetz', 'marlaberggoetz63@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Mariann', 'Jacobson', 'mariannjacobson@gmail.com', 90.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Marianne', 'Brown', 'marianne@deaflink.net', 85.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Marina', 'Epstein', 'terpmaryna@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Mary', 'Madia', 'mbm.visualcommunication@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Mary Kay', 'Adams', 'mkadamsnyc@gmail.com', 70.00, 80.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Marybeth', 'Imsho', 'statenislandasl@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Maureen', 'Roan', 'maureenroan@gmail.com', 75.00, NULL, NULL, NULL, NULL, 'RID# 42942', 'zelle', 'active'),
  ('Megan', 'Morgan', 'megan@openmindinterpreting.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Melanie', 'Garten', 'masgarten@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Melina', 'Gaglioti', 'melinarosegaglioti@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Melissa', 'Jenkins', 'mcerqua83@hotmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Melissa', 'Treadwell', 'tea4238@gmail.com', 45.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Melissa', 'Poore', 'lissapoore@gmail.com', 45.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Meredith', 'DeLeon', 'meredith.a.t@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Meryl', 'Troop', 'meryltroop@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Michael', 'Mendes', 'michael.labadie.mendes@gmail.com', 65.00, NULL, NULL, NULL, NULL, 'RID# 18115', 'zelle', 'active'),
  ('Michael', 'Miille', 'mjmiille@gmail.com', 60.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Michael', 'McMillion', 'mcmillion_m@yahoo.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Michana', 'Baise', 'michanab7@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Michelle', 'Doyle', 'mldoyle80@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Michelle', 'Zeitlin', 'michellejzeitlin@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Michelle', 'Rimmer', 'mrimmer71@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Michelle', 'Monahan', 'michellejmonahan@gmail.com', 90.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Miriam', 'Morrow', 'morrow.miriam@gmail.com', 80.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Monica', 'Nativo', 'monicanativo@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Morgan', 'Johansen', 'mjohansen.interpreter@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Morgan', 'Wongsuwan', 'mwongsuwan@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Myron', 'Yoder', 'myronyoder@aol.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Nancy', 'Kaplan', 'nek36terp4u@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Nancy', 'Cronk-Walker', 'nancronkwalker@aol.com', 65.00, NULL, NULL, NULL, NULL, 'RID# 17323', 'zelle', 'active'),
  ('Nicole', 'Cartagna', 'interpretopia@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Nicole', 'Cordeau', 'Nmcord@gmail.com', 60.00, 75.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Nicole', 'Pancino', 'nvpmobile@gmail.com', 70.00, NULL, NULL, NULL, NULL, 'RID# 34368', 'zelle', 'active'),
  ('Nicole', 'Safford', 'nmsafford08@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Nikki', 'Wells', 'talkwithurhands@yahoo.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Nina', 'Sturmer', 'ninasturmer@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Norma', 'Villegas', 'tianormalita@icloud.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Nydia', 'Hernandez', 'nyd65@optonline.net', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Pamela', 'Ashe', 'providedbypamela@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Pamela', 'DOcchio', 'pladocchio@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Pat', 'Pomerance', 'parp65@msn.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Rockett', 'Unknown', 'p.rockett2020@gmail.com', 35.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Patrick', 'Cole', 'pcinasl@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Paul', 'Bauer', 'paul.bauer@verizon.net', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Paul', 'Lambert', 'sdterponcall@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Paula', 'Tucker', 'pettucker@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Paulina', 'Burnham', 'pburnham.terp@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Phyllis', 'Rifkin', 'pdrifkin@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Quinn', 'Bankler', 'quinnbanklerasl@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Rachel', 'Colaprete', 'fullstreamrr@gmail.com', 65.00, NULL, NULL, NULL, NULL, 'RID# 11329', 'zelle', 'active'),
  ('Raymond', 'Baesler', 'flyingr@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Rebecca', 'Breisacher', 'rebeccanice@niceinterpreters.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Rebecca', 'Friedman', 'interpreterbec@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Regina', 'Henriquez', 'ginseng06@hotmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Rene', 'Bane', 'rene.bane.asl@icloud.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Rick', 'Haffner', 'rlh28269@att.net', 80.00, NULL, NULL, NULL, NULL, 'BEI#18353, no zelle/ send check', 'check', 'active'),
  ('Robbie', 'Smith', 'robbie.yanna@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Robert', 'LoParo', 'bob.loparo@yahoo.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Robin', 'Hunter', 'robinsinterpreting@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Robyn', 'Karimi', 'robyn.karimi@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Roni', 'LePore', 'ramshamllc97@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Roy', 'Hensley', 'hensley2542@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Ryann', 'Perkins', 'perkinsryann@gmail.com', 90.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Sam', 'Zampelli', 'samzampelli.interpreting@gmail.com', 65.00, 70.00, NULL, NULL, NULL, 'RID# 89886', 'zelle', 'active'),
  ('Sandi', 'Nelson', 'sandi.grey.nelson@gmail.com', 65.00, NULL, NULL, NULL, NULL, 'RID# 68760', 'zelle', 'active'),
  ('Sandra', 'Canas', 'sandraromerocanas@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Sandy', 'Brown', 'sbblue3@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Sara', 'Kaufman', 'signingsara@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Sarah', 'Campbell', 'sarahacamp720@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Shelley', 'Hardlell', 'spectruminterpreting@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Shelly', 'Comfort', 'smcomfort@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Sheryl', 'Fernandez', 'sfdancer7@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Shirley', 'Moore', 'shirsignndesign@gmail.com', 65.00, NULL, NULL, NULL, NULL, 'RID# 20013', 'zelle', 'active'),
  ('Simon', 'Martinez', 'simonmartinezjr23@gmail.com', 83.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Sirena', 'Lemieux', 'lemieux.sirena@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Solee', 'Natal', 'soleenatal@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Stacie', 'Angelo', 'stacieangelo@live.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Stacie', 'Rubin', 'stacey.r@me.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Stacie', 'Gibson', 'sg7494@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Stacy', 'Frueh', 'sfrueh@comcast.net', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Stefanie', 'Lewis', 'stef3asl@aol.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Stephanie', 'Gage', 'sgage65@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Stephanie', 'Kanieski', 'signingsteph@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Stephanie', 'Bonales', 'stephanielbonales@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Stephanie', 'De La Cruz', 'sdelacruz.interp@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Stephen', 'Palmer', 'scr.palmer@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Steven', 'Westbrook', 'office@beheardasl.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Sue', 'Sommers', 'slsommers@comcast.net', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Susan', 'McGroarty', 'susanmcgroarty@yahoo.com', 65.00, NULL, NULL, NULL, NULL, 'RID# 23639', 'zelle', 'active'),
  ('Susan', 'Scholz', 'slscholz@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Susanna', 'Wobbrock', 'sjoywobbrock@gmail.com', 50.00, NULL, '801 8th St. NW Trlr 128', 'Little Falls', 'MN', NULL, 'zelle', 'active'),
  ('Susie', 'Devergranne', 'aslworks@baymoon.com', 80.00, NULL, NULL, NULL, NULL, 'RID# 43552', 'zelle', 'active'),
  ('Suzanne', 'Dunleavy', 'sdunleavy@verizon.net', 60.00, NULL, NULL, NULL, NULL, 'no zelle/ send check', 'check', 'active'),
  ('Tabatha', 'King', 'tking7984@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Tammy', 'Scoggin', 'tammyscoggintass@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Tammy', 'Cantrell', 'tammyscantrell@gmail.com', 50.00, NULL, '5120 Arrowshire Dr', 'LaGrange', 'KY', 'no zelle/ send check', 'check', 'active'),
  ('Tara', 'Marino', 'taraterps@gmail.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Tari', 'Kelly', 'tarikelley@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Terri', 'Chapman', 'terri.chapman@gemission.org', 55.00, NULL, NULL, NULL, NULL, 'RID# 19517', 'zelle', 'active'),
  ('Terry', 'Safay', 'terrysafay@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Theresa', 'Bulger', 'tbugler@me.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Tiffany', 'Mosquera', 'asl_interpreter@verizon.net', 60.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Tiffany', 'Narducci', 'tiffanya424@aol.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Tim', 'Smith', 'timterpllc@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Toni', 'Kretzmer', 'tonikret@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Tracey', 'Ridlon', 'tridlon07@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Tracey', 'Romanow', 'tdromanow@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Tracey', 'Davis', 'traceydav67@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Tracy', 'Norris', 'norris.interpreting@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Tricia', 'Dolan', 'triciad415@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Tricia', 'Osborn', 'lovesymbol@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Valencia', 'Nicholls', 'vc.jm.nicholls@gmail.com', 60.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Vanessa', 'Gallo', 'vgallo1120@yahoo.com', 65.00, 70.00, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Vanessa', 'Klein', 'aslterp24@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Victoria', 'Napoles', 'victoria.lozano.terp@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Vincent', 'Sylvester', 'vsylvester427@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Wanic', 'Polynice', 'wanic.poly@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Whitney', 'Rice', 'rice_whitney@yahoo.com', 70.00, 80.00, NULL, NULL, NULL, 'RID# 56219', 'zelle', 'active'),
  ('Whitney', 'Upshur', 'w.upshur4life@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Whitney', 'Rese', 'wreese09@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Zahirah', 'Perez', 'zmptranslations@gmail.com', 40.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Megan', 'Ferris', 'megan.ferris88@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Janet', 'Maxwell', 'codaterp68@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Alicia', 'Schwabacher', 'asigninghand@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Mary', 'Moylan', 'mmoylan31@gmail.com', 85.00, NULL, NULL, NULL, NULL, 'Business name: Hand Talk Inc', 'zelle', 'active'),
  ('Jessica', 'Chaput', 'jesstures@gmail.com', 67.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Nancy', 'Decman', 'nancydecman@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lixa', 'Pustelnik', 'thelixa@gmail.com', 80.00, NULL, NULL, NULL, NULL, 'RID# 15668', 'zelle', 'active'),
  ('Monica', 'Carmona', 'blancalu7@yahoo.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Patricia', 'Wiest', 'pmckitrick333@hotmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Rachel', 'Groner', 'rjgroner@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lori', 'Green', 'terplgreen@gmail.com', 65.00, NULL, '7600 Sara Lynn Way', 'Citrus Heights', 'Ca', 'no zelle/ send check', 'check', 'active'),
  ('Breeann', 'Katz', 'breekatz.bk@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('SeQuoyia', 'Jackson', 'seqjackson@gmail.com', 50.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Barbara', 'Coffan', 'coffanb@juno.com', 55.00, NULL, '165 Drumcliff Ct', 'Tyrone', 'GA', 'RID# 11312, no zelle/ send check', 'check', 'active'),
  ('Tironica', 'Hamilton', 'tironica@aol.com', 75.00, NULL, NULL, NULL, NULL, '24 hour cancelation', 'zelle', 'active'),
  ('Mary', 'Wisbey', 'maryterp@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kati', 'Krause', 'kdk_signs@yahoo.com', 80.00, NULL, NULL, NULL, NULL, 'RID# 65376', 'zelle', 'active'),
  ('Kelli', 'Pomphrey', 'kellipomphrey@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Christy', 'Lechuga', 'christy.lechuga@yahoo.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Randee', 'Pascall-Speights', 'rpascallspeights@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kimberly', 'Hernandez', 'kfarinha@gmail.com', 90.00, NULL, NULL, NULL, NULL, 'RID# 39088', 'zelle', 'active'),
  ('Vincent', 'James', 'vrjinterpret@sonic.net', 70.00, NULL, NULL, NULL, NULL, 'RID# 38266', 'zelle', 'active'),
  ('Michael', 'Ahimsa', 'aslterpmichael@gmail.com', 100.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kathi', 'Neuenschwander', 'kathineuen@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Fern', 'Gilbreath', 'terpferngee@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Cynthia', 'Ramirez', 'cindyramirezinterpreting@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Moira', 'Sweeney', 'moiragrace24@gmail.com', 60.00, NULL, NULL, NULL, NULL, 'RID# 30600', 'zelle', 'active'),
  ('Dana', 'Fuller', 'danamfuller@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Raquel', 'Puente', 'rapuente4@gmail.com', 75.00, NULL, NULL, NULL, NULL, 'non cert', 'zelle', 'active'),
  ('Jesse', 'Dorland', 'jessedorland.asl@gmail.com', 67.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Justine', 'Jones', 'messison5@aol.com', 65.00, NULL, NULL, NULL, NULL, 'RID# 34780', 'zelle', 'active'),
  ('Tara', 'Furcini', 'getbeyondlanguage@gmail.com', 85.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jessica', 'Poitevin', 'jessicasigns@gmail.com', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lori', 'Patton', 'loribpatton3@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Sheryl', 'Cooper', 'fingerworks1@gmail.com', 68.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Brenda', 'Pluntze', 'bpluntze@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Diana', 'Abayeva', 'dianaabayeva@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Amanda', 'Vallario', 'amanda.vallario@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('April', 'Perry', 'interpreterasl@earthlink.net', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Emma', 'Sills', 'esinterpreter@gmail.com', 60.00, NULL, '2741 62nd Ter N, Apt A', 'St. Petersburg', 'Fl', 'RID# 91078', 'check', 'active'),
  ('Autumn', 'Thomas', 'autumnthomasasl@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('LaShaundra', 'Lewis', 'yumpmax@gmail.com', 75.00, NULL, NULL, NULL, NULL, 'RID# 78612', 'zelle', 'active'),
  ('Debbie', 'Rice', 'riceterp@gmail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Ariana', 'Fisher', 'terpalf@gmail.com', 65.00, NULL, NULL, NULL, NULL, 'RID# 65765', 'zelle', 'active'),
  ('Caleigh', 'Collins', 'ccollins954@bellsouth.net', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Samantha', 'Ettlin', 'srettlin@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Scott', 'Cawley', 'cawley.scotty@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lindy', 'Zornoza', 'garciaterp6@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Valerie', 'Kline', 'valkline@ymail.com', 60.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Farrah', 'Nolan-Black', 'farrah@touchfinish.net', 80.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Debra', 'Marich-Fox', 'damterp71@yahoo.com', 60.00, NULL, NULL, NULL, NULL, 'RID# 27342', 'zelle', 'active'),
  ('Sue Ann', 'Pope', 'popebay4@yahoo.com', 60.00, NULL, NULL, NULL, NULL, 'RID# 38809', 'zelle', 'active'),
  ('Laura', 'Keen', 'keen_laura@yahoo.com', 80.00, NULL, NULL, NULL, NULL, 'RID# 35283', 'zelle', 'active'),
  ('Mark', 'Weissglass', 'markweissglass@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Chris', 'Johnson', 'chrisjohnson@codatrue.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Kate', 'Livingston', 'aslterp831@comcast.net', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Lisa', 'Dignan', 'lisadignan@gmail.com', 70.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Anthony', 'Holle', 'codatones00@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jina', 'DiNardo', 'jinadinardo@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Aleksandr', 'Rozentsvit', 'aleksandr.rozentsvit@gmail.com', 65.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Christine', 'Mizrahi', 'camizrahi@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Amanda', 'Mendez', 'amariemendez1213@gmail.com', 40.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Trenton', 'Marsh', 'trentonmarshcdi@gmail.com', 75.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Terri', 'Neal', 'pageterri@gmail.com', 55.00, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active'),
  ('Jennifer', 'Flint', 'jflint23@live.com', NULL, NULL, NULL, NULL, NULL, NULL, 'zelle', 'active')
ON CONFLICT DO NOTHING;