-- Mark specified facilities as contractors
UPDATE public.facilities SET contractor = true WHERE name IN (
  'Acees Partners- Julian',
  'Acolad',
  'Ad Astra',
  'ALS Global American Language Services',
  'Andre Turcios',
  'Bridges- Access Jason',
  'Capital Linguistics',
  'Certified Interpreters CIS',
  'Courtside Interpreting',
  'Cq Fluency',
  'Day Translation',
  'Deafinite Solutions',
  'Dhcc- Philly agency',
  'Eiber Translations',
  'Excel Lingistics',
  'Globo',
  'Go T&T',
  'Health Plus Trans',
  'HomeLinks',
  'International Languages',
  'Interprenet',
  'Language Doctor',
  'Language Solutions',
  'Languages Unlimited',
  'Languuager',
  'Legacy Dance',
  'Legal Languages',
  'Legal Languages Medical',
  'LM Language Services',
  'LNG Consulting',
  'Lourdes',
  'LTC Language Solutions',
  'Magnus',
  'Mej',
  'Neptune School District',
  'NY Start Program',
  'PCCS- Person Centered Care Services',
  'Preffered Services',
  'Pro Health Dental',
  'ProCare',
  'Production Glue',
  'ProHealth Circle',
  'Project Hospitality',
  'Project HospitalityHome Health Services',
  'Richmond Rehab',
  'Rise Dance Studio',
  'Rumc',
  'Rumc Amboy',
  'Service Bridges',
  'St Johns',
  'T&T Staffing',
  'The integrity Company',
  'Toms Riveer HS South',
  'Total Captioning',
  'Transperfect',
  'Tribeca Dental',
  'TTG- TransAtlantic',
  'Turn it up',
  'Ubiquis',
  'Ubiquis Legal',
  'VNA of SI',
  'Wall Social Services',
  'Wee Care Pediatrics',
  'Woodbridge Township',
  'Carteret School District',
  'NYC Department of Veterans'' Services',
  'Pronto Translastion',
  'Lionbridge',
  'Nuanced Interpretation LLC',
  'Language Link',
  'CCI- Multilingual'
);